spring.application.name=personal-ai-assistant

server.port=8080



# ==========================
# Database Configuration
# ==========================

spring.datasource.url=jdbc:mariadb://localhost:3306/aiAssistant

spring.datasource.username=root

spring.datasource.password=root

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ==========================
# Hibernate
# ==========================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false




spring.ai.ollama.base-url=http://localhost:11434

spring.ai.ollama.chat.options.temperature=0.0


# =========================
# Qdrant
# =========================

spring.ai.vectorstore.qdrant.host=localhost

spring.ai.vectorstore.qdrant.port=6334

spring.ai.vectorstore.qdrant.collection-name=healthcare_documents

spring.ai.vectorstore.qdrant.initialize-schema=true


####################################################
# Ollama Chat Model
####################################################

spring.ai.ollama.chat.options.model=qwen3:8b

####################################################
# Ollama Embedding Model
####################################################

spring.ai.ollama.embedding.options.model=nomic-embed-text